version: '3'
services:
  postgres:
    build: ./postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - postgres/db.env
  test_postgres:
    image: postgres:9.6-alpine
    restart: always
    env_file:
      - postgres/db.env
    volumes:
      - ./postgres:/root/
  web:
    build: ./php
    volumes:
      - ./php/src/:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - postgres
      - test_postgres
volumes:
  db-data:
